[build]
  publish = "public"
  functions = "netlify/functions"

# This forces Netlify to bundle Python dependencies
[functions]
  node_bundler = "none"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200